name: "Build iOS app"

# on: [push]
on: [workflow_dispatch]

jobs:
  build_ios:
    runs-on: macos-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive and ipaify
        run: |
          wget -O archive.zip "https://dl.dropboxusercontent.com/scl/fi/qg4ofedro2xsr0wtyz6sd/ios.zip?rlkey=avw6jlbtcztrenumz9wb2nwd9&dl=1"
          unzip archive.zip -d .

          xcodebuild archive -project godot_ios.xcodeproj -scheme 'godot_ios' -archivePath godot_ios.xcarchive -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO

          mkdir Payload
          mv Example-Project.xcarchive/Products/Applications/godot_ios.app Payload/godot_ios.app

          zip -r "godot_ios.ipa" "Payload"

          mv godot_ios.ipa ${{ runner.temp }}/godot_ios.ipa


      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: godot_ios
          path: ${{ runner.temp }}/godot_ios.ipa
          # you can also archive the entire directory
          # path: ${{ runner.temp }}/build
          retention-days: 3
